name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          install.packages(c("devtools", "roxygen2", "testthat", "covr", "janitor", "glue", "jsonlite", "purrr", "tibble"))
          devtools::install_deps(dependencies = TRUE)

      - name: Run R CMD check
        run: |
          devtools::check()

      - name: Run test coverage
        run: |
          covr::report()
